[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
sbi-rt = "0.0.3"
bitflags = "2.4.2"
xmas-elf = "0.9.1"
SyscallAPI = { path = "api" }

[lib]
crate-type = ["staticlib"]


[profile.release]
debug = 2

[workspace]
members = [
	"user_program",
	"api"
]
